services:
  front:
    container_name: scoreboard-front
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - back

  back:
    container_name: scoreboard-back
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: scoreboard-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
